import {
  Client,
  Technician,
  Ticket,
  Quotation,
  DashboardMetrics,
  Notification,
} from "./types";

export const mockClients: Client[] = [
  {
    id: "c1",
    name: "Grupo Industrial Soriana",
    email: "contacto@soriana.com",
    phone: "81-1234-5678",
    company: "Soriana S.A.",
    address: "Av. Universidad 1200",
    city: "Monterrey",
    active: true,
    createdAt: "2024-01-15",
  },
  {
    id: "c2",
    name: "TecnoFarma SA de CV",
    email: "soporte@tecnofarma.mx",
    phone: "81-2345-6789",
    company: "TecnoFarma",
    address: "Calle Reforma 450",
    city: "Monterrey",
    active: true,
    createdAt: "2024-02-20",
  },
  {
    id: "c3",
    name: "Hospital Universitario",
    email: "mantenimiento@hospital.universitario.mx",
    phone: "81-3456-7890",
    company: "Hospital Universitario",
    address: "Av. Madero 800",
    city: "Monterrey",
    active: true,
    createdAt: "2024-03-10",
  },
  {
    id: "c4",
    name: "Restaurante La Parrilla",
    email: "admin@laparrilla.mx",
    phone: "81-4567-8901",
    address: "Calle Hidalgo 230",
    city: "San Pedro",
    active: true,
    createdAt: "2024-04-05",
  },
  {
    id: "c5",
    name: "Constructora del Norte",
    email: "ops@delnorte.com",
    phone: "81-5678-9012",
    company: "Del Norte S.A.",
    address: "Blvd. Díaz Ordaz 1500",
    city: "Guadalupe",
    active: true,
    createdAt: "2024-05-12",
  },
  {
    id: "c6",
    name: "AutoLavado Express",
    email: "info@autolavado.mx",
    phone: "81-6789-0123",
    address: "Av. Constitución 670",
    city: "Monterrey",
    active: true,
    createdAt: "2024-06-18",
  },
];

export const mockTechnicians: Technician[] = [
  {
    id: "t1",
    name: "Carlos Mendoza",
    email: "carlos@jetrack.mx",
    phone: "81-1111-2222",
    role: "technician",
    specialty: "Electrónica Industrial",
    zone: "Norte",
    availability: "en_trabajo",
    rating: 4.8,
    completedJobs: 156,
    active: true,
  },
  {
    id: "t2",
    name: "Roberto García",
    email: "roberto@jetrack.mx",
    phone: "81-2222-3333",
    role: "technician",
    specialty: "Plomería",
    zone: "Sur",
    availability: "disponible",
    rating: 4.6,
    completedJobs: 132,
    active: true,
  },
  {
    id: "t3",
    name: "Miguel Torres",
    email: "miguel@jetrack.mx",
    phone: "81-3333-4444",
    role: "technician",
    specialty: "Climatización",
    zone: "Este",
    availability: "disponible",
    rating: 4.9,
    completedJobs: 198,
    active: true,
  },
  {
    id: "t4",
    name: "Juan Luis Pérez",
    email: "juan@jetrack.mx",
    phone: "81-4444-5555",
    role: "technician",
    specialty: "Mantenimiento General",
    zone: "Centro",
    availability: "fuera",
    rating: 4.5,
    completedJobs: 89,
    active: true,
  },
  {
    id: "t5",
    name: "Alejandro Ruiz",
    email: "alex@jetrack.mx",
    phone: "81-5555-6666",
    role: "technician",
    specialty: "Electricidad",
    zone: "Oeste",
    availability: "en_trabajo",
    rating: 4.7,
    completedJobs: 145,
    active: true,
  },
];

export const mockTickets: Ticket[] = [
  {
    id: "TK-001",
    title: "Reparación de aire acondicionado",
    description:
      "Unidad central no enfría. Se requiere diagnóstico y reparación del compresor.",
    status: "en_camino",
    priority: "alta",
    clientId: "c1",
    clientName: "Grupo Industrial Soriana",
    technicianId: "t1",
    technicianName: "Carlos Mendoza",
    serviceType: "Climatización",
    scheduledDate: "2026-07-21",
    scheduledTime: "09:00",
    location: "Av. Universidad 1200, Monterrey",
    estimatedDuration: 120,
    photos: [],
    notes: [
      {
        id: "n1",
        content: "Cliente reporta ruido extraño desde hace 3 días",
        author: "María López",
        authorRole: "supervisor",
        createdAt: "2026-07-20T14:30:00",
        isInternal: false,
      },
    ],
    createdAt: "2026-07-20T10:00:00",
    updatedAt: "2026-07-21T08:15:00",
    createdBy: "María López",
  },
  {
    id: "TK-002",
    title: "Instalación de sistema eléctrico",
    description:
      "Instalación de tablero eléctrico nuevo para expansión de oficina.",
    status: "scheduled",
    priority: "media",
    clientId: "c2",
    clientName: "TecnoFarma SA de CV",
    technicianId: "t5",
    technicianName: "Alejandro Ruiz",
    serviceType: "Electricidad",
    scheduledDate: "2026-07-22",
    scheduledTime: "10:00",
    location: "Calle Reforma 450, Monterrey",
    estimatedDuration: 240,
    photos: [],
    notes: [],
    quotationId: "Q-001",
    createdAt: "2026-07-19T16:00:00",
    updatedAt: "2026-07-19T16:00:00",
    createdBy: "María López",
  },
  {
    id: "TK-003",
    title: "Mantenimiento preventivo caldera",
    description:
      "Mantenimiento preventivo trimestral de caldera industrial marca Bosch.",
    status: "completado",
    priority: "media",
    clientId: "c3",
    clientName: "Hospital Universitario",
    technicianId: "t3",
    technicianName: "Miguel Torres",
    serviceType: "Mantenimiento",
    scheduledDate: "2026-07-18",
    scheduledTime: "08:00",
    startedAt: "2026-07-18T08:15:00",
    completedAt: "2026-07-18T11:45:00",
    actualDuration: 210,
    location: "Av. Madero 800, Monterrey",
    estimatedDuration: 180,
    photos: [
      {
        id: "p1",
        url: "/placeholder-before.jpg",
        type: "antes",
        caption: "Estado inicial de la caldera",
        uploadedAt: "2026-07-18T08:20:00",
      },
      {
        id: "p2",
        url: "/placeholder-after.jpg",
        type: "despues",
        caption: "Caldera después del mantenimiento",
        uploadedAt: "2026-07-18T11:40:00",
      },
    ],
    signature: "data:image/png;base64,signature-placeholder",
    notes: [
      {
        id: "n2",
        content: "Se reemplazaron 2 válvulas de control de presión",
        author: "Miguel Torres",
        authorRole: "technician",
        createdAt: "2026-07-18T10:30:00",
        isInternal: false,
      },
    ],
    createdAt: "2026-07-15T09:00:00",
    updatedAt: "2026-07-18T11:45:00",
    createdBy: "María López",
  },
  {
    id: "TK-004",
    title: "Fuga de agua en cocina",
    description:
      "Fuga significativa bajo el lavamanos. Se requiere reparación urgente.",
    status: "iniciado",
    priority: "urgente",
    clientId: "c4",
    clientName: "Restaurante La Parrilla",
    technicianId: "t2",
    technicianName: "Roberto García",
    serviceType: "Plomería",
    scheduledDate: "2026-07-21",
    scheduledTime: "07:30",
    startedAt: "2026-07-21T07:45:00",
    location: "Calle Hidalgo 230, San Pedro",
    estimatedDuration: 90,
    photos: [],
    notes: [
      {
        id: "n3",
        content: "Emergencia - restaurante cerrado por la fuga",
        author: "Admin",
        authorRole: "admin",
        createdAt: "2026-07-21T07:00:00",
        isInternal: true,
      },
    ],
    createdAt: "2026-07-21T06:30:00",
    updatedAt: "2026-07-21T07:45:00",
    createdBy: "María López",
  },
  {
    id: "TK-005",
    title: "Instalación de paneles solares",
    description:
      "Instalación de 12 paneles solares en azotea con inversor y baterías.",
    status: "scheduled",
    priority: "baja",
    clientId: "c5",
    clientName: "Constructora del Norte",
    technicianId: "t1",
    technicianName: "Carlos Mendoza",
    serviceType: "Eléctrico Solar",
    scheduledDate: "2026-07-25",
    scheduledTime: "06:00",
    location: "Blvd. Díaz Ordaz 1500, Guadalupe",
    estimatedDuration: 480,
    photos: [],
    notes: [],
    quotationId: "Q-002",
    createdAt: "2026-07-10T11:00:00",
    updatedAt: "2026-07-10T11:00:00",
    createdBy: "María López",
  },
  {
    id: "TK-006",
    title: "Reparación de sistema de seguridad",
    description:
      "Cámaras CCTV no funcionan en estacionamiento. Posible problema en DVR.",
    status: "pausado",
    priority: "alta",
    clientId: "c6",
    clientName: "AutoLavado Express",
    technicianId: "t4",
    technicianName: "Juan Luis Pérez",
    serviceType: "Seguridad",
    scheduledDate: "2026-07-20",
    scheduledTime: "14:00",
    startedAt: "2026-07-20T14:10:00",
    pausedAt: "2026-07-20T15:30:00",
    location: "Av. Constitución 670, Monterrey",
    estimatedDuration: 180,
    photos: [],
    notes: [
      {
        id: "n4",
        content: "Pausado - esperando repuesto DVR que llega mañana",
        author: "Juan Luis Pérez",
        authorRole: "technician",
        createdAt: "2026-07-20T15:30:00",
        isInternal: false,
      },
    ],
    createdAt: "2026-07-19T09:00:00",
    updatedAt: "2026-07-20T15:30:00",
    createdBy: "María López",
  },
  {
    id: "TK-007",
    title: "Cambio de iluminación LED",
    description:
      "Reemplazo de 40 tuberos fluorescentes por LED en nave de producción.",
    status: "pending",
    priority: "baja",
    clientId: "c1",
    clientName: "Grupo Industrial Soriana",
    serviceType: "Electricidad",
    scheduledDate: "2026-07-28",
    scheduledTime: "06:00",
    location: "Av. Universidad 1200, Monterrey",
    estimatedDuration: 360,
    photos: [],
    notes: [],
    createdAt: "2026-07-18T13:00:00",
    updatedAt: "2026-07-18T13:00:00",
    createdBy: "María López",
  },
  {
    id: "TK-008",
    title: "Reparación de bomba de agua",
    description:
      "Bomba principal de agua presenta fallas intermitentes. Requiere diagnóstico.",
    status: "completado",
    priority: "alta",
    clientId: "c3",
    clientName: "Hospital Universitario",
    technicianId: "t2",
    technicianName: "Roberto García",
    serviceType: "Plomería",
    scheduledDate: "2026-07-17",
    scheduledTime: "09:00",
    startedAt: "2026-07-17T09:10:00",
    completedAt: "2026-07-17T13:20:00",
    actualDuration: 250,
    location: "Av. Madero 800, Monterrey",
    estimatedDuration: 240,
    photos: [],
    signature: "data:image/png;base64,signature-placeholder-2",
    notes: [],
    createdAt: "2026-07-14T08:00:00",
    updatedAt: "2026-07-17T13:20:00",
    createdBy: "María López",
  },
];

export const mockQuotations: Quotation[] = [
  {
    id: "Q-001",
    number: "COT-2026-001",
    title: "Instalación tablero eléctrico - TecnoFarma",
    status: "aprobada",
    clientId: "c2",
    clientName: "TecnoFarma SA de CV",
    technicianId: "t5",
    technicianName: "Alejandro Ruiz",
    items: [
      {
        id: "qi1",
        description: "Tablero eléctrico 200A con protecciones",
        quantity: 1,
        unitPrice: 15000,
        total: 15000,
      },
      {
        id: "qi2",
        description: "Cableado THW #6 ( metros)",
        quantity: 50,
        unitPrice: 85,
        total: 4250,
      },
      {
        id: "qi3",
        description: "Mano de obra instalación",
        quantity: 1,
        unitPrice: 12000,
        total: 12000,
      },
    ],
    subtotal: 31250,
    tax: 4999.99,
    total: 36249.99,
    validUntil: "2026-08-15",
    notes: "Incluye materiales y mano de obra. Garantía de 1 año.",
    ticketId: "TK-002",
    createdAt: "2026-07-18T10:00:00",
    updatedAt: "2026-07-19T14:00:00",
    approvedAt: "2026-07-19T14:00:00",
  },
  {
    id: "Q-002",
    number: "COT-2026-002",
    title: "Instalación paneles solares - Constructora del Norte",
    status: "enviada",
    clientId: "c5",
    clientName: "Constructora del Norte",
    items: [
      {
        id: "qi4",
        description: "Panel solar 400W monocristalino",
        quantity: 12,
        unitPrice: 4500,
        total: 54000,
      },
      {
        id: "qi5",
        description: "Inversor híbrido 5kW",
        quantity: 1,
        unitPrice: 22000,
        total: 22000,
      },
      {
        id: "qi6",
        description: "Batería LiFePO4 100Ah",
        quantity: 4,
        unitPrice: 8500,
        total: 34000,
      },
      {
        id: "qi7",
        description: "Estructura de montaje y riel",
        quantity: 1,
        unitPrice: 18000,
        total: 18000,
      },
      {
        id: "qi8",
        description: "Instalación y cableado",
        quantity: 1,
        unitPrice: 25000,
        total: 25000,
      },
    ],
    subtotal: 153000,
    tax: 24480,
    total: 177480,
    validUntil: "2026-08-30",
    notes:
      "Sistema autónomo sin conexión a CFE. Incluye permisos y conexión.",
    ticketId: "TK-005",
    createdAt: "2026-07-10T14:00:00",
    updatedAt: "2026-07-12T09:00:00",
  },
  {
    id: "Q-003",
    number: "COT-2026-003",
    title: "Mantenimiento preventivo anual - Hospital",
    status: "borrador",
    clientId: "c3",
    clientName: "Hospital Universitario",
    items: [
      {
        id: "qi9",
        description: "Revisión y calibración de equipos HVAC",
        quantity: 1,
        unitPrice: 35000,
        total: 35000,
      },
      {
        id: "qi10",
        description: "Limpieza de ductos principales",
        quantity: 1,
        unitPrice: 20000,
        total: 20000,
      },
    ],
    subtotal: 55000,
    tax: 8800,
    total: 63800,
    validUntil: "2026-09-30",
    createdAt: "2026-07-20T11:00:00",
    updatedAt: "2026-07-20T11:00:00",
  },
];

export const mockMetrics: DashboardMetrics = {
  totalTickets: 247,
  activeTickets: 18,
  completedToday: 5,
  pendingTickets: 12,
  revenue: 385000,
  avgCompletionTime: 195,
  clientSatisfaction: 4.7,
  technicianUtilization: 82,
};

export const mockNotifications: Notification[] = [
  {
    id: "notif1",
    title: "Ticket urgente asignado",
    message: "TK-004 asignado a Roberto García - Fuga en restaurante",
    type: "warning",
    read: false,
    createdAt: "2026-07-21T06:30:00",
  },
  {
    id: "notif2",
    title: "Trabajo completado",
    message: "TK-003 completado por Miguel Torres - Hospital Universitario",
    type: "success",
    read: false,
    createdAt: "2026-07-18T11:45:00",
  },
  {
    id: "notif3",
    title: "Cotización aprobada",
    message: "COT-2026-001 aprobada por TecnoFarma - $36,249.99",
    type: "success",
    read: true,
    createdAt: "2026-07-19T14:00:00",
  },
  {
    id: "notif4",
    title: "Técnico en pausa",
    message: "Juan Luis Pérez pausó TK-006 - Esperando repuesto",
    type: "info",
    read: true,
    createdAt: "2026-07-20T15:30:00",
  },
  {
    id: "notif5",
    title: "Nueva cotización pendiente",
    message: "COT-2026-002 enviada a Constructora del Norte - $177,480",
    type: "info",
    read: true,
    createdAt: "2026-07-12T09:00:00",
  },
];

export const serviceTypes = [
  "Climatización",
  "Electricidad",
  "Plomería",
  "Mantenimiento",
  "Seguridad",
  "Eléctrico Solar",
  "Telecomunicaciones",
  "Carpintería",
  "Pintura",
  "Limpieza Industrial",
];
